<a href="https://colab.research.google.com/github/de-fernandez/CPE-313-CPE32S3/blob/main/Don%20Eleazar%20T.%20Fernandez%2C%20CPE32S3%2C%20CPE%20313%20(Discussion%205.1%20-%20NLP%20Preprocessing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Discussion** **5.1** | **NLP** **Preprocessing**

Submit the screenshots of your source codes and output




*  Tokenize (words)
* Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)
*  Tokenize (words with remove punctuation and all lowercase)
* Tokenize (words with remove punctuation, all lowercase and remove stop words)
* Tokenize (words with remove punctuation, all lowercase and  remove stop words, with speech_tagging)

In [1]:
import pandas as pd
import nltk
import string
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/CPE 313/H.O.A. 8.1/Corona.csv', encoding='latin1')
data = data.drop(columns = ['ScreenName', 'Location', 'TweetAt'])
data.head()

,UserName,OriginalTweet,Sentiment
0,3799,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,advice Talk to your neighbours family to excha...,Positive
2,3801,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,My food stock is not the only one which is emp...,Positive
4,3803,"Me, ready to go at supermarket during the #COV...",Extremely Negative

In [4]:
data = data[['UserName', 'OriginalTweet']].head(100)
data_text = data['OriginalTweet']

Tokenize (words)

In [5]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

data['tokens'] = data_text.apply(lambda x: word_tokenize(x))
data.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,UserName,OriginalTweet,tokens
0,3799,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,"[@, MeNyrbie, @, Phil_Gahan, @, Chrisitv, http..."
1,3800,advice Talk to your neighbours family to excha...,"[advice, Talk, to, your, neighbours, family, t..."
2,3801,Coronavirus Australia: Woolworths to give elde...,"[Coronavirus, Australia, :, Woolworths, to, gi..."
3,3802,My food stock is not the only one which is emp...,"[My, food, stock, is, not, the, only, one, whi..."
4,3803,"Me, ready to go at supermarket during the #COV...","[Me, ,, ready, to, go, at, supermarket, during..."

Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)

In [6]:
import re
from nltk.tokenize import word_tokenize

# Remove punctuation
data['tokens_no_punct'] = data_text.apply(lambda x: word_tokenize(x.translate(str.maketrans('', '', string.punctuation))))

# Remove special characters & numbers
data['tokens_no_special'] = data_text.apply(lambda x: word_tokenize(re.sub(r'[^A-Za-z\s]', '', x)))

data.head()

,UserName,OriginalTweet,tokens,tokens_no_punct,tokens_no_special
0,3799,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,"[@, MeNyrbie, @, Phil_Gahan, @, Chrisitv, http...","[MeNyrbie, PhilGahan, Chrisitv, httpstcoiFz9FA...","[MeNyrbie, PhilGahan, Chrisitv, httpstcoiFzFAn..."
1,3800,advice Talk to your neighbours family to excha...,"[advice, Talk, to, your, neighbours, family, t...","[advice, Talk, to, your, neighbours, family, t...","[advice, Talk, to, your, neighbours, family, t..."
2,3801,Coronavirus Australia: Woolworths to give elde...,"[Coronavirus, Australia, :, Woolworths, to, gi...","[Coronavirus, Australia, Woolworths, to, give,...","[Coronavirus, Australia, Woolworths, to, give,..."
3,3802,My food stock is not the only one which is emp...,"[My, food, stock, is, not, the, only, one, whi...","[My, food, stock, is, not, the, only, one, whi...","[My, food, stock, is, not, the, only, one, whi..."
4,3803,"Me, ready to go at supermarket during the #COV...","[Me, ,, ready, to, go, at, supermarket, during...","[Me, ready, to, go, at, supermarket, during, t...","[Me, ready, to, go, at, supermarket, during, t..."

Tokenize (words with remove punctuation and all lowercase)

In [7]:
data['tokens_lower'] = data['tokens_no_punct'].apply(lambda x: [w.lower() for w in x])
data['tokens_lower'].head()

0    [menyrbie, philgahan, chrisitv, httpstcoifz9fa...
1    [advice, talk, to, your, neighbours, family, t...
2    [coronavirus, australia, woolworths, to, give,...
3    [my, food, stock, is, not, the, only, one, whi...
4    [me, ready, to, go, at, supermarket, during, t...
Name: tokens_lower, dtype: object

Tokenize (words with remove punctuation, all lowercase and remove stop words)

In [8]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
data['tokens_no_stop'] = data['tokens_lower'].apply(lambda x: [w for w in x if w not in stop_words])
data['tokens_no_stop'].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

0    [menyrbie, philgahan, chrisitv, httpstcoifz9fa...
1    [advice, talk, neighbours, family, exchange, p...
2    [coronavirus, australia, woolworths, give, eld...
3    [food, stock, one, empty, please, dont, panic,...
4    [ready, go, supermarket, covid19, outbreak, im...
Name: tokens_no_stop, dtype: object

Tokenize (words with remove punctuation, all lowercase and remove stop words, with speech_tagging)

In [10]:
from nltk import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

data['tokens_pos'] = data['tokens_no_stop'].apply(lambda x: nltk.pos_tag(x))
data['tokens_pos'].head()

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

0    [(menyrbie, NN), (philgahan, NN), (chrisitv, N...
1    [(advice, NN), (talk, NN), (neighbours, IN), (...
2    [(coronavirus, NN), (australia, NNS), (woolwor...
3    [(food, NN), (stock, NN), (one, CD), (empty, J...
4    [(ready, JJ), (go, VBP), (supermarket, JJ), (c...
Name: tokens_pos, dtype: object